#!/usr/bin/env python3
"""
Plan sparse 2D navigation waypoints from occupancy grid.
Constraints:
  - obstacle avoidance
  - each segment is straight line
  - segment length <= max_segment_m (default 10.0m)
  - as few waypoints as possible (via post-sparsification)

Input map: .npz generated by build_grid_map.py
"""

from __future__ import annotations

import argparse
import heapq
import json
import math
from pathlib import Path

import numpy as np


def world_to_grid(x: float, y: float, origin: np.ndarray, res: float) -> tuple[int, int]:
    gx = int(math.floor((x - origin[0]) / res))
    gy = int(math.floor((y - origin[1]) / res))
    return gx, gy


def grid_to_world(gx: int, gy: int, origin: np.ndarray, res: float) -> tuple[float, float]:
    x = origin[0] + (gx + 0.5) * res
    y = origin[1] + (gy + 0.5) * res
    return x, y


def in_bounds(gx: int, gy: int, width: int, height: int) -> bool:
    return 0 <= gx < width and 0 <= gy < height


def line_is_free(occ: np.ndarray, a: tuple[int, int], b: tuple[int, int]) -> bool:
    """Bresenham collision check on grid cells."""
    x0, y0 = a
    x1, y1 = b

    dx = abs(x1 - x0)
    dy = abs(y1 - y0)
    sx = 1 if x0 < x1 else -1
    sy = 1 if y0 < y1 else -1
    err = dx - dy

    h, w = occ.shape
    x, y = x0, y0
    while True:
        if not in_bounds(x, y, w, h):
            return False
        if occ[y, x] != 0:
            return False
        if x == x1 and y == y1:
            break
        e2 = 2 * err
        if e2 > -dy:
            err -= dy
            x += sx
        if e2 < dx:
            err += dx
            y += sy
    return True


def astar(occ: np.ndarray, start: tuple[int, int], goal: tuple[int, int]) -> list[tuple[int, int]]:
    h, w = occ.shape
    if not in_bounds(start[0], start[1], w, h) or not in_bounds(goal[0], goal[1], w, h):
        raise ValueError("Start or goal out of map bounds")
    if occ[start[1], start[0]] != 0:
        raise ValueError("Start lies in obstacle")
    if occ[goal[1], goal[0]] != 0:
        raise ValueError("Goal lies in obstacle")

    neigh = [
        (-1, 0, 1.0),
        (1, 0, 1.0),
        (0, -1, 1.0),
        (0, 1, 1.0),
        (-1, -1, math.sqrt(2.0)),
        (-1, 1, math.sqrt(2.0)),
        (1, -1, math.sqrt(2.0)),
        (1, 1, math.sqrt(2.0)),
    ]

    def heuristic(a: tuple[int, int], b: tuple[int, int]) -> float:
        return math.hypot(a[0] - b[0], a[1] - b[1])

    g_cost: dict[tuple[int, int], float] = {start: 0.0}
    came_from: dict[tuple[int, int], tuple[int, int]] = {}
    open_heap: list[tuple[float, tuple[int, int]]] = [(heuristic(start, goal), start)]
    closed: set[tuple[int, int]] = set()

    while open_heap:
        _, cur = heapq.heappop(open_heap)
        if cur in closed:
            continue
        closed.add(cur)

        if cur == goal:
            path = [cur]
            while cur in came_from:
                cur = came_from[cur]
                path.append(cur)
            path.reverse()
            return path

        cx, cy = cur
        for dx, dy, step in neigh:
            nx, ny = cx + dx, cy + dy
            nxt = (nx, ny)
            if not in_bounds(nx, ny, w, h):
                continue
            if occ[ny, nx] != 0:
                continue

            # For diagonal motion, avoid corner cutting.
            if dx != 0 and dy != 0:
                if occ[cy, nx] != 0 or occ[ny, cx] != 0:
                    continue

            ng = g_cost[cur] + step
            if ng < g_cost.get(nxt, float("inf")):
                g_cost[nxt] = ng
                came_from[nxt] = cur
                f = ng + heuristic(nxt, goal)
                heapq.heappush(open_heap, (f, nxt))

    raise RuntimeError("No path found")


def sparsify_path(
    occ: np.ndarray,
    path: list[tuple[int, int]],
    res: float,
    max_segment_m: float,
) -> list[tuple[int, int]]:
    if len(path) <= 2:
        return path

    max_cells = int(math.floor(max_segment_m / res))
    out = [path[0]]
    i = 0
    n = len(path)

    while i < n - 1:
        best_j = i + 1
        # Greedy farthest jump satisfying collision-free + max distance
        j = i + 1
        while j < n:
            dx = path[j][0] - path[i][0]
            dy = path[j][1] - path[i][1]
            dist_cells = math.hypot(dx, dy)
            if dist_cells > max_cells:
                break
            if line_is_free(occ, path[i], path[j]):
                best_j = j
                j += 1
            else:
                break

        out.append(path[best_j])
        i = best_j

    return out


def yaw_quat_from_to(a_xy: tuple[float, float], b_xy: tuple[float, float]) -> tuple[float, float, float, float]:
    yaw = math.atan2(b_xy[1] - a_xy[1], b_xy[0] - a_xy[0])
    qz = math.sin(yaw * 0.5)
    qw = math.cos(yaw * 0.5)
    return 0.0, 0.0, qz, qw


def main() -> None:
    parser = argparse.ArgumentParser(description="Plan sparse 2D path from occupancy map")
    parser.add_argument("--map", required=True, help="Input .npz map from build_grid_map.py")
    parser.add_argument("--start", nargs=2, type=float, required=True, metavar=("X", "Y"))
    parser.add_argument("--goal", nargs=2, type=float, required=True, metavar=("X", "Y"))
    parser.add_argument("--goal-yaw", type=float, default=0.0, help="Goal yaw in radians")
    parser.add_argument("--max-segment", type=float, default=10.0, help="Max segment length (m)")
    parser.add_argument("--output", required=True, help="Output JSON path")
    args = parser.parse_args()

    data = np.load(args.map)
    occ = data["occupancy"].astype(np.uint8)
    origin = data["origin"].astype(np.float64)
    res = float(data["resolution"][0])

    sx, sy = args.start
    gx, gy = args.goal

    s_grid = world_to_grid(sx, sy, origin, res)
    g_grid = world_to_grid(gx, gy, origin, res)

    dense = astar(occ, s_grid, g_grid)
    sparse = sparsify_path(occ, dense, res, max_segment_m=args.max_segment)

    world_pts = [grid_to_world(px, py, origin, res) for px, py in sparse]

    waypoints = []
    for i, (x, y) in enumerate(world_pts):
        if i < len(world_pts) - 1:
            qx, qy, qz, qw = yaw_quat_from_to((x, y), world_pts[i + 1])
        else:
            qx, qy, qz, qw = 0.0, 0.0, math.sin(args.goal_yaw * 0.5), math.cos(args.goal_yaw * 0.5)

        waypoints.append(
            {
                "index": i,
                "x": x,
                "y": y,
                "z": 0.0,
                "qx": qx,
                "qy": qy,
                "qz": qz,
                "qw": qw,
            }
        )

    # Validate segment length
    for i in range(len(waypoints) - 1):
        dx = waypoints[i + 1]["x"] - waypoints[i]["x"]
        dy = waypoints[i + 1]["y"] - waypoints[i]["y"]
        seg = math.hypot(dx, dy)
        if seg > args.max_segment + 1e-6:
            raise RuntimeError(f"Segment {i}->{i+1} exceeds max length: {seg:.3f}m")

    out_obj = {
        "map": str(Path(args.map).resolve()),
        "start": {"x": sx, "y": sy},
        "goal": {"x": gx, "y": gy, "yaw": args.goal_yaw},
        "max_segment": args.max_segment,
        "num_waypoints": len(waypoints),
        "waypoints": waypoints,
    }

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(out_obj, ensure_ascii=False, indent=2), encoding="utf-8")

    print("Path planned:", out_path)
    print("Dense nodes:", len(dense), "Sparse waypoints:", len(sparse))


if __name__ == "__main__":
    main()
