#!/bin/bash

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source "${SCRIPT_DIR}/path_env.sh"
source py310/bin/activate

export ROS_MASTER_URI=${RABBITBOT_ROS_MASTER_URI:-http://kuavo_master:11311}
export ROS_IP=${RABBITBOT_ROS_IP:-192.168.26.13}
export ROS_HOSTNAME=${RABBITBOT_ROS_HOSTNAME:-${ROS_IP}}

source /opt/ros/foxy/setup.bash
source "${RABBITBOT_VLN_WS_DIR}/install/setup.bash"

export CUR_DIR=$(pwd)
cd "${RABBITBOT_PYORBBEC_DIR}"
export PYTHONPATH=$PYTHONPATH:$(pwd)/install/lib/
cd ${CUR_DIR}

export PYTHONPATH=/usr/local/lib:$(pwd):${PYTHONPATH}

echo ${PYTHONPATH}

export RABBITBOT_MODEL_SERVER=${RABBITBOT_MODEL_SERVER:-http://127.0.0.1:8000/v1}
export RABBITBOT_VLN_URL=${RABBITBOT_VLN_URL:-http://127.0.0.1:8001}
export RABBITBOT_MEMORY_AGENT_URL=${RABBITBOT_MEMORY_AGENT_URL:-http://127.0.0.1:28182}
export RABBITBOT_ROBOT_AGENT_URL=${RABBITBOT_ROBOT_AGENT_URL:-http://localhost:28180}
export REALTIME_STT_BASE_URL=${REALTIME_STT_BASE_URL:-http://localhost:28184/v1}
export REALTIME_TTS_BASE_URL=${REALTIME_TTS_BASE_URL:-http://localhost:28185/v1}
export RABBITBOT_STT_AGENT_URL=${RABBITBOT_STT_AGENT_URL:-${REALTIME_STT_BASE_URL}}
export RABBITBOT_TTS_AGENT_URL=${RABBITBOT_TTS_AGENT_URL:-${REALTIME_TTS_BASE_URL}}
export RABBITBOT_INTERRUPT_RMS_THRESHOLD=${RABBITBOT_INTERRUPT_RMS_THRESHOLD:-0.02}
export OUTPUT_DEVICE_INDEX=${OUTPUT_DEVICE_INDEX:-25}

py310/bin/python scripts/run_kuavo_agno_workflow.py --patch
